#ifndef VRT_CONFIG_H
#define VRT_CONFIG_H

#define VRT_MAX_TASKS 8
#define VRT_MAX_TASKS_TOTAL (VRT_MAX_TASKS + 1)

#define VRT_STACK_SIZE 1024
#define VRT_STACK_ALIGNMENT 16u
#define VRT_TASK_NAME_LENGTH 16

#define VRT_BASE_SAVE_AREA_SIZE 0x20u

#endif