#include <Arduino.h>

#include "vrt_scheduler.h"
#include "vrt_task.h"

/*
 * ============================================================================
 * VertexRT STEP 7
 * Two-task voluntary context-switch test
 *
 * Purpose:
 *
 *   A starts
 *     -> A yields
 *     -> B starts
 *     -> inspect A's saved XtSolFrame
 *     -> B yields
 *     -> A should resume
 *
 * We are specifically diagnosing the A -> B -> A transition.
 * ============================================================================
 */

static vrt_task_t taskA;
static vrt_task_t taskB;

static uint32_t stackA[VRT_STACK_SIZE];
static uint32_t stackB[VRT_STACK_SIZE];

static volatile uint32_t countA = 0;
static volatile uint32_t countB = 0;

/*
 * ============================================================================
 * Task A
 * ============================================================================
 */

static void task_a(void *argument)
{
    (void)argument;

    Serial.println();
    Serial.println("========== TASK A STARTED ==========");

    for (;;)
    {
        countA++;

        Serial.printf(
            "A: %lu\n",
            (unsigned long)countA);

        Serial.println("A: yielding");

        /*
         * First time through this creates A's solicited Xtensa frame.
         *
         * When Task A is eventually restored, execution should continue
         * at the instruction immediately after this call.
         */
        vrt_task_yield();

        Serial.println("A: resumed");
    }
}

/*
 * ============================================================================
 * Task B
 * ============================================================================
 *
 * B inspects A's saved stack after the first A -> B switch.
 * ============================================================================
 */

static void task_b(void *argument)
{
    (void)argument;

    Serial.println();
    Serial.println("========== TASK B STARTED ==========");

    for (;;)
    {
        countB++;

        Serial.printf(
            "B: %lu\n",
            (unsigned long)countB);

        /*
         * --------------------------------------------------------------------
         * Inspect Task A's saved solicited frame.
         * --------------------------------------------------------------------
         *
         * At this point Task A has already yielded, so taskA.sp should point
         * at the XtSolFrame generated by vrt_port_yield_switch().
         */
        if (taskA.sp != nullptr)
        {
            uint32_t *p = taskA.sp;

            Serial.println();
            Serial.println("=== TASK A SAVED FRAME ===");

            Serial.printf(
                "SP   = %p\n",
                (void *)p);

            Serial.printf(
                "[00] = 0x%08lx  EXIT\n",
                (unsigned long)p[0]);

            Serial.printf(
                "[01] = 0x%08lx  PC\n",
                (unsigned long)p[1]);

            Serial.printf(
                "[02] = 0x%08lx  PS\n",
                (unsigned long)p[2]);

            Serial.printf(
                "[03] = 0x%08lx\n",
                (unsigned long)p[3]);

            Serial.printf(
                "[04] = 0x%08lx\n",
                (unsigned long)p[4]);

            Serial.printf(
                "[05] = 0x%08lx\n",
                (unsigned long)p[5]);

            Serial.printf(
                "[06] = 0x%08lx\n",
                (unsigned long)p[6]);

            Serial.printf(
                "[07] = 0x%08lx\n",
                (unsigned long)p[7]);

            Serial.println("============================");
        }
        else
        {
            Serial.println(
                "ERROR: Task A SP is NULL.");
        }

        Serial.println("B: yielding");

        /*
         * This is the transition that currently crashes:
         *
         *     B -> A
         *
         * We want to know what exactly is stored in A's saved frame before
         * this happens.
         */
        vrt_task_yield();

        Serial.println("B: resumed");
    }
}

/*
 * ============================================================================
 * Setup
 * ============================================================================
 */

void setup()
{
    Serial.begin(115200);
    delay(1000);

    Serial.println();
    Serial.println("====================================");
    Serial.println("VertexRT STEP 7");
    Serial.println("Two-task voluntary switch test");
    Serial.println("====================================");

    /*
     * ------------------------------------------------------------------------
     * Scheduler
     * ------------------------------------------------------------------------
     */

    vrt_scheduler_t *scheduler =
        vrt_scheduler_get_instance();

    if (scheduler == nullptr)
    {
        Serial.println(
            "ERROR: scheduler instance is NULL.");

        while (true)
        {
            delay(1000);
        }
    }

    Serial.println(
        "Initializing scheduler...");

    vrt_scheduler_init(scheduler);

    Serial.println(
        "Scheduler initialized.");

    /*
     * ------------------------------------------------------------------------
     * Task A
     * ------------------------------------------------------------------------
     */

    Serial.println(
        "Initializing Task A...");

    vrt_task_init(
        &taskA,
        task_a,
        nullptr,
        1,
        stackA,
        VRT_STACK_SIZE,
        "taskA");

    Serial.printf(
        "Task A SP = %p\n",
        (void *)taskA.sp);

    if (taskA.sp == nullptr)
    {
        Serial.println(
            "ERROR: Task A initialization failed.");

        while (true)
        {
            delay(1000);
        }
    }

    Serial.println(
        "Task A initialized.");

    /*
     * ------------------------------------------------------------------------
     * Task B
     * ------------------------------------------------------------------------
     */

    Serial.println(
        "Initializing Task B...");

    vrt_task_init(
        &taskB,
        task_b,
        nullptr,
        1,
        stackB,
        VRT_STACK_SIZE,
        "taskB");

    Serial.printf(
        "Task B SP = %p\n",
        (void *)taskB.sp);

    if (taskB.sp == nullptr)
    {
        Serial.println(
            "ERROR: Task B initialization failed.");

        while (true)
        {
            delay(1000);
        }
    }

    Serial.println(
        "Task B initialized.");

    /*
     * ------------------------------------------------------------------------
     * Add Task A
     * ------------------------------------------------------------------------
     */

    if (!vrt_scheduler_add_task(
            scheduler,
            &taskA))
    {
        Serial.println(
            "ERROR: Could not add Task A.");

        while (true)
        {
            delay(1000);
        }
    }

    Serial.println(
        "Task A added.");

    /*
     * ------------------------------------------------------------------------
     * Add Task B
     * ------------------------------------------------------------------------
     */

    if (!vrt_scheduler_add_task(
            scheduler,
            &taskB))
    {
        Serial.println(
            "ERROR: Could not add Task B.");

        while (true)
        {
            delay(1000);
        }
    }

    Serial.println(
        "Task B added.");

    /*
     * ------------------------------------------------------------------------
     * Start scheduler
     * ------------------------------------------------------------------------
     */

    Serial.println();
    Serial.println(
        "Starting VertexRT scheduler...");

    vrt_scheduler_start(scheduler);

    /*
     * Should never return.
     */
    Serial.println(
        "ERROR: Scheduler returned.");

    while (true)
    {
        delay(1000);
    }
}

/*
 * ============================================================================
 * Arduino loop
 * ============================================================================
 */

void loop()
{
    /*
     * VertexRT should have taken over before Arduino loop() is reached.
     */
    Serial.println(
        "ERROR: Arduino loop() running.");

    delay(1000);
}